---
---
<font size="3">

## **Hi, I'm Sushmita!**
</br>
<p align="justify">
I'm a decision scientist at <a href="https://www.grubhub.com/lets-eat"> Grubhub</a>, based out of Chicago. I analyse experiments and conduct simulation studies to help make business decisions. An important part of my job is to advocate for statistical rigour in various decision-making processes within the company.
</p>
<p align="justify">
Prior to this, I was a data scientist at the <a href="https://sites.northwestern.edu/n3lab/about/"> Northwestern Neighborhood and Network Initiative </a> at Northwestern University. I used statistics, network science and machine learning to work on a variety of projects on gun violence and police misconduct in Chicago. As N3's first data science hire, I also worked on setting up computing infrastructure and data pipelines for the lab.  
</p>
<p align="justify">
I'm proud to be a co-organizer at the wonderful <a href = "https://rladieschicago.org/"> Chicago chapter</a> of R-Ladies. R-Ladies is a global support and advocacy group for women and gender minorities who use R. We now have a presence in 149 cities across the world and over 50,000 members!
</p>
<p align="justify">
I arrived at data science by way of Economics at the Indian Institute of Technology Madras (<a href = 'https://www.iitm.ac.in/'>IIT-M</a>), policy research at the Institute for Financial Management and Research (<a href='http://ifmrlead.org/'>IFMR</a>), and <a href='https://macss.uchicago.edu/'>Computational Social Science</a> at the University of Chicago. I'm easily excited by the application of statistical and computational methods in public health, media and popular culture. 
</p>
<p align="justify">
You can contact me on <a href='https://twitter.com/SushGopalan'> Twitter</a>, <a href='https://www.linkedin.com/in/sushmita-v-gopalan-280010a4/'> LinkedIn</a>, or at sushmitavgopalan@gmail.com.
</p>

<br /><br /><br /><br /><br /><br /><br /><br /><br /><br /><br /><br /><br /><br /><br /><br /><br /><br /><br /><br /><br /><br /><br /><br /><br/>
<br /><br /><br /><br /><br /><br /><br /><br /><br /><br /><br /><br /><br /><br /><br /><br /><br /><br /><br /><br /><br /><br /><br /><br /><br/>
<br /><br /><br /><br /><br /><br /><br /><br /><br /><br /><br /><br /><br /><br /><br /><br /><br /><br /><br /><br /><br /><br /><br /><br /><br/>